services:
  db:
    hostname: db
    image: mariadb:11.3.2
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: change_root_psw
      MYSQL_DATABASE: NOTEX
      MYSQL_USER: DEV
      MYSQL_PASSWORD: change_dev_psw
    ports:
      - 3306:3306
    expose:
      - 3306
  backend:
    hostname: backend
    image: tomcat:9.0
    restart: always
    volumes:
      - ./backend/server.xml:/usr/local/tomcat/conf/server.xml
      - ./backend/build/libs/notex_backend.war:/usr/local/tomcat/webapps/notex_backend.war
      - ./frontend/build:/usr/local/tomcat/webapps/notex_frontend
      - ./frontend/WEB-INF:/usr/local/tomcat/webapps/notex_frontend/WEB-INF
    ports:
      - 8080:8080