const usersMock = [
    {
      username: "user1",
      password: "password",
      score   : 4.25,
      notebooks: [
        {
          username: "user1",
          name: "notebook1",
          score: 4.5,
          tags: [],
          notes: [
            {
              username: "user1",
              notebook: "notebook1",
              name: "note1",
              score: 5,
              tags: [],
              reviews: [],
              serverContextFile: "https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
            {
              username: "user1",
              notebook: "notebook1",
              name: "note2",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
          ],
        },
        {
          username: "user1",
          name: "notebook2",
          score: 4,
          tags: [],
          notes: [
            {
              username: "user1",
              notebook: "notebook2",
              name: "note3",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
            {
              username: "user1",
              notebook: "notebook2",
              name: "note4",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
          ],
        },
      ],
    },
    {
      username: "user2",
      password: "password",
      score   : 4.25,
      notebooks: [
        {
          username: "user2",
          name: "notebook3",
          score: 4.5,
          tags: [],
          notes: [
            {
              username: "user2",
              notebook: "notebook3",
              name: "note5",
              score: 5,
              tags: [],
              reviews: [],
              serverContextFile: "https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
            {
              username: "user2",
              notebook: "notebook3",
              name: "note6",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
          ],
        },
        {
          username: "user2",
          name: "notebook4",
          score: 4,
          tags: [],
          notes: [
            {
              username: "user2",
              notebook: "notebook4",
              name: "note7",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
            {
              username: "user2",
              notebook: "notebook4",
              name: "note8",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
          ],
        },
      ],
    },
    {
      username: "user3",
      password: "password",
      score   : 4.25,
      notebooks: [
        {
          username: "user3",
          name: "notebook5",
          score: 4.5,
          tags: [],
          notes: [
            {
              username: "user3",
              notebook: "notebook5",
              name: "note9",
              score: 5,
              tags: [],
              reviews: [],
              serverContextFile: "https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
            {
              username: "user3",
              notebook: "notebook5",
              name: "note10",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
          ],
        },
        {
          username: "user3",
          name: "notebook6",
          score: 4,
          tags: [],
          notes: [
            {
              username: "user3",
              notebook: "notebook6",
              name: "note11",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
            {
              username: "user3",
              notebook: "notebook6",
              name: "note12",
              score: 4,
              tags: [],
              reviews: [],
              https:"https://b3nny01.github.io/NoteX",
              filePath: "exampleNote.pdf",
            },
          ],
        },
      ],
    },
    
  ];

  export default usersMock;